global:
 resolve_timeout: 5m
 telegram_api_url: "https://api.telegram.org"

templates:
  - '/etc/alertmanager/*.tmpl'

route:
 group_by: ['ds_id'] # Алерты группируются по UUID кластера.
 group_wait: 15s
 group_interval: 30s
 repeat_interval: 12h
 receiver: telepush
 routes:
  - receiver: telepush
    continue: true
    matchers:
     - severity="critical"

receivers:
  - name: 'telepush'
    telegram_configs:
    - chat_id: -1002320304683
      bot_token: 7318583911:AAGF7muIujx5bU-r3B75XGyXK9PBBLJjU9g
      api_url: "https://api.telegram.org"
      send_resolved: true
      parse_mode: HTML
      message: '{{ template "telegram.default" . }}'
