groups:
 - name: node_exporter
   rules:
     - alert: InstanceDown
       expr: up{job="node_exporter"}  == 0
       for: 0m
       labels:
         severity: critical
       annotations:
         summary: "Сервер {{ $labels.instance }} недоступен!"

     - alert: InstancePostgreSQLDown
       expr: pg_up{job="pg_exporter"}  == 0
       for: 0m
       labels:
         severity: critical
       annotations:
         summary: "Сервер СУБД {{ $labels.instance }} недоступен!"
